eclipse/eclipse-collections-kata

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
- Fixed description in exercise 2.
- Fixed setup for exercise 5.
> Minor fixes to pet kata.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
Signed-off-by: Kristen O'Leary <kristen.oleary@gs.com>
> Fix Javadoc for Exercise5Test.

- company-kata/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata/src/main/java/org/eclipse/collections/companykata/LineItem.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Order.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Supplier.java
- company-kata/src/test/java/org/eclipse/collections/companykata/CompanyDomainForKata.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise3Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise4Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
Signed-off-by: Kristen O'Leary <kristen.oleary@gs.com>
> Add solutions branch.

- README.md
Linking to pdf slides for now. We will replace them with web hosted slides along the way. 
This should be merged to solution branch soon, too. Current solution branch has "WIP" notes that look odd.
> Add links to slides and solution branch.

- README.md
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
Minimize the differences between master and solutions so that the only remaining diffs are related to completing exercises.
> Merge master into solutions.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
Fixed a minor typo in a test name.
> Corrected minor typo.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
I'm learn about eclipse-collections-kata by using Pet Kata.
I found an answer already written in Exercise5Test. 
I think it is not be written in Exercise5Test. Plz check it!
> delete answer in Exercise5Test

- docs/pet-kata/slides.md
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
> Clean up Exercise1Test and link to JavaDoc for methods and Html slides.

- docs/pet-kata/slides.md
> Fix typo and scrolling issue in slides.

- README.md
Signed-off-by: Frank Dietrich <frank.dietrich@gmx.li>
> add instruction for Netbeans users

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
> Updated Exercise2Test for PetKata.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
> Update Exercise3Test in PetKata.

- docs/slides.md
> Add Company Kata to index.

- docs/company-kata/slides.md
> Add slides to Company Kata up through Exercise 8 Solutions.

- README.md
> Add logo and Company Kata slides to readme.

- docs/company-kata/slides.md
- docs/pet-kata/slides.md
- docs/setup/slides.md
> Update slides with collection factories and clean up logos.

- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise3Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise4Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- docs/company-kata/slides.md
> Update exercises with links to slide content.

- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
> Improve Excercise1Test in Company Kata.

- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Update JavaDoc in exercises.

- .idea/libraries/Maven__org_eclipse_collections_eclipse_collections_9_1_0.xml
- .idea/libraries/Maven__org_eclipse_collections_eclipse_collections_api_9_1_0.xml
- .idea/libraries/Maven__org_eclipse_collections_eclipse_collections_testutils_9_1_0.xml
> Add EC 9.1.xml files for Maven.

- README.md
- docs/api-design/slides.md
> Update the readme.md file.

- docs/api-design/slides.md
> Update slides for API Design talk.

- README.md
- docs/company-kata/slides.md
- docs/pet-kata/slides.md
> Update images in markdown files.

- docs/api-design/slides.md
> Updated API Design slides with 9.2 release info.

- docs/api-design/slides.md
> Updated API Design slides with detect, detectIfNone, detectOptional.

- README.md
> Make logo smaller in README.md.

- README.md
> Add badges to README.md.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
take 4
Signed-off-by: Matthias Cullmann <matthias.cullmann@gmail.com>
> getAllPetsOfAllPeople -> getAllPetTypesOfAllPeople

- docs/pet-kata/slides.md
> Update PetKata slides to match exercises.

- build.gradle
- pom.xml
- settings.gradle
> Update Eclipse Collections dependencies to 10.0.0.M3.

- build.gradle
- pom.xml
> Upgrade to Eclipse Collections 10.0.0.

- docs/company-kata/slides.md
> Updated Company Kata slides.

- build.gradle
- pom.xml
Upgraded Eclipse Collections from 10.0.0 to 10.1.0
> Upgraded Eclipse Collections to 10.1.0

- docs/api-design/slides.md
> Fixed formatting issues in API design slides.

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Clean up Exercise4Test.

- .github/workflows/maven.yml
> Adding github action flow for EC Kata

- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Update copyright in Exercise4Test.

- README.md
> Add GitHub Actions badge to README.md.

- pom.xml
Signed-off-by: Alexander Goldberg <alexander.goldberg@bnymellon.com>
> updated EC version to 10.2.0

- company-kata/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Order.java
> Minor cleanup of domain classes in CompanyKata.

- .github/workflows/maven.yml
- .travis.yml
- pom.xml
> Upgrade Eclipse Collections Kata to Java 11

- .idea/misc.xml
- candy-kata/src/test/java/org/eclipse/collections/candykata/CandyKataTest.java
- candy-kata/src/test/java/org/eclipse/collections/candykata/solutions/CandyKataSolutionsTest.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise3Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise4Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
> Update katas to use local variable type inference.

- README.md
> Updating README to add requirements for JDK 11 and Maven

- .idea/compiler.xml
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
> Updating pet-kata solutions to use local variable type inference

- .github/workflows/maven.yml
> Adding Github Action for running tests in solution modules.

- README.md
> Remove Travis Build references in README

- .github/workflows/maven.yml
- candy-kata-solutions/pom.xml
- candy-kata-solutions/src/main/java/org/eclipse/collections/candykata/Candy.java
- candy-kata-solutions/src/main/java/org/eclipse/collections/candykata/SchoolGroup.java
- candy-kata-solutions/src/test/java/org/eclipse/collections/candykata/CandyKataSolutionsTest.java
- pom.xml
> Adding candy-kata solutions module

- company-kata-solutions/pom.xml
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/LineItem.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Order.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Supplier.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/CompanyDomainForKata.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise3Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise4Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- pom.xml
> Adding company-kata-solutions module

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise3Test.java
Signed-off-by: John Stuart <john.stuart@bnymellon.com>
closes #110
> Submit Excercise3Test solutions

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
Signed-off-by: Rafael E. Gonzalez <rafael.gonzalez@bnymellon.com>
> Implement solution for CompanyKata. This closes #109

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
> Solutions for Exercise1Test. Closes #108

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
> Remove unused import

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
Signed-off-by: Christopher Taylor <christopher.a.taylor@bnymellon.com>
> Add solutions for Exercise 5.

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Order.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
Signed-off-by: Nikhil Kharche <nikhil.kharche@gmail.com>
Solutions for Exercise8Test mentioned in #115
> Solution for Excercise8Test.java

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
Signed-off-by: nsardana-bny <neha.sardana@bnymellon.com>
Closes #113
> Add solutions to Exercise6Test.java. Closes #113

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
> Minor improvements to Exercise8 solutions of Company Kata.

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise6Test.java
> Minor improvements to Exercise6 solutions of Company Kata.

- candy-kata-solutions/pom.xml
- candy-kata-solutions/src/main/java/org/eclipse/collections/candykata/Candy.java
- candy-kata-solutions/src/main/java/org/eclipse/collections/candykata/SchoolGroup.java
- candy-kata-solutions/src/test/java/org/eclipse/collections/candykata/CandyKataSolutionsTest.java
- candy-kata/pom.xml
- candy-kata/src/main/java/org/eclipse/collections/candykata/Candy.java
- candy-kata/src/main/java/org/eclipse/collections/candykata/SchoolGroup.java
- candy-kata/src/test/java/org/eclipse/collections/candykata/CandyKataTest.java
- docs/api-design/index.html
- docs/api-design/slides.md
> Updated copyright.

- .github/workflows/maven.yml
Signed-off-by: Xiangdong Xu <xiangdong.xu@bnymellon.com>
closes #131
> add company-kata-solutions to github actions. closes 131

- .github/workflows/solutions.yml
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- pom.xml
> Update Eclipse Collections version to 10.3.0.M1

- docs/company-kata/slides.md
Signed-off-by: Richard Scott <richard.scott@bnymellon.com>
> Closes #123: Updated links to solutions.

- pom.xml
Signed-off-by: Rodrigo Graciano <rodrigo.graciano@bnymellon.com>
> Closes #140: Upgrade Eclipse Collections to 10.3.0.M3

- docs/setup/slides.md
- pet-kata/README.md
> Add README to pet-kata. Closes #136

- README.md
Signed-off-by: Matthew Dietz <Matthew.Dietz@bnymellon.com>
> Add Candy Kata to README section. closes ticket #133

- pom.xml
Signed-off-by: Stan Podolski <stanislav.podolski@bnymellon.com>
> Closes #147: Upgrade Eclipse Collections to 10.3.0.M4

- pom.xml
Closes #155
Signed-off-by: Dustin Williams <dustin.williams@bnymellon.com>
> Update Eclipse Collections to 10.3.0.M5 closes #155

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise8Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Refactor katas to use newer JDK APIs and cleanup hints.

- pom.xml
Signed-off-by: Richard Duffett <richard.duffett@bnymellon.com>
> Upgrade to Eclipse Collections 10.4.0. Closes #160.

- docs/api-design/slides.md
> Update api-design slides with latest release information.

- docs/pet-kata/slides.md
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
Found some minor inconsistencies in the pet-kata exercise 4.
The exercise asks for using minIfEmpty, maxIfEmpty, averageIfEmpty, but the solution does not use these methods
The solution contains some extra tests, but the exercise does not give any information about these extra tests
Updated the exercise 4 documentation, it was not in line with the source code of the solution
This is my first contribution to an Eclipse Foundations project.
> Pet kata ex4 inconsistencies

- .github/workflows/solutions.yml
- README.md
- converter-method-kata-solutions/pom.xml
- converter-method-kata-solutions/src/main/java/org/eclipse/collections/convertermethodkata/Person.java
- converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/CollectorsToCollectionsTest.java
- converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/IntIterableToCollectionsTest.java
- converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToCollectionsTest.java
- converter-method-kata/README.md
- converter-method-kata/pom.xml
- converter-method-kata/src/main/java/org/eclipse/collections/convertermethodkata/Person.java
- converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/CollectorsToCollectionsTest.java
- converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/IntIterableToCollectionsTest.java
- converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToCollectionsTest.java
- pom.xml
> Add Converter Method Kata.

- converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToImmutableCollectionsTest.java
- converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/RichIterableToImmutableCollectionsTest.java
> Add RichIterableToImmutableCollectionsTest to Converter Method Kata.

- converter-method-kata-solutions/src/test/java/org/eclipse/collections/convertermethodkata/CollectorsToImmutableCollectionsTest.java
- converter-method-kata/src/test/java/org/eclipse/collections/convertermethodkata/CollectorsToImmutableCollectionsTest.java
> Add CollectorsToImmutableCollectionsTest to Converter Method Kata.

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise4Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise5Test.java
- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise7Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise2Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise5Test.java
> Cleanup formatting issues.

- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
> Clean up solutions for Exercise 3 of Pet Kata.

- pet-kata-solutions/src/main/java/org/eclipse/collections/petkata/Person.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Clean up solutions for Exercise 4 of Pet Kata.

- .github/workflows/solutions.yml
- pom.xml
- top-methods-kata-solutions/pom.xml
- top-methods-kata-solutions/src/main/java/org/eclipse/collections/topmethodskata/Fruit.java
- top-methods-kata-solutions/src/test/java/org.eclipse.collections.topmethodskata/Top25MethodsTest.java
> Add solutions module for new Top Methods Kata.

- pom.xml
- top-methods-kata-solutions/src/test/java/org/eclipse/collections/topmethodskata/Top25MethodsTest.java
- top-methods-kata/README.md
- top-methods-kata/pom.xml
- top-methods-kata/src/main/java/org/eclipse/collections/topmethodskata/Fruit.java
- top-methods-kata/src/test/java/org/eclipse/collections/topmethodskata/Top25MethodsTest.java
> Add the module for the Top Methods kata.

- README.md
> Update README.md with Top Methods Kata.

- candy-kata/README.md
> Fix typo in Candy Kata README.md.

- docs/pet-kata/slides.md
Fix for issue 134: Replace Solutions in pet-kata slides.md with Links to Solutions Module.
> Fix for issue 134: Replace Solutions in pet-kata slides.md with Links to Solutions Module.

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Company.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/LineItem.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Order.java
- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Supplier.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata/src/main/java/org/eclipse/collections/companykata/LineItem.java
- pet-kata-solutions/src/main/java/org/eclipse/collections/petkata/Person.java
- pet-kata/src/main/java/org/eclipse/collections/petkata/Person.java
> Minor cleanup refactoring.

- .github/workflows/solutions.yml
- lost-and-found-kata-solutions/pom.xml
- lost-and-found-kata-solutions/src/main/java/org/eclipse/collections/lostandfoundkata/primitive/MinMaxPrimitivesBoxed.java
- lost-and-found-kata-solutions/src/main/java/org/eclipse/collections/lostandfoundkata/primitive/MinMaxPrimitivesPlain.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/AbstractThreadSafeCollectionsTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/MultiReaderCollectionsTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/SynchronizedCollectionsTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/BoxingTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/CollectionMemoryTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntBagTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntIntMapTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntListTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntStackTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/LazyIntIterableTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/StringAdaptersTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntBagTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntIntMapTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntSetTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntStackTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/SynchronizedIntListTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/UnmodifiableIntListTest.java
- pom.xml
> Add initial solutions for new Lost and Found Kata.

- lost-and-found-kata/pom.xml
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/AbstractThreadSafeCollectionsTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/MultiReaderCollectionsTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/SynchronizedCollectionsTest.java
- pom.xml
> Add multireader tests for Lost and Found Kata.

- lost-and-found-kata/README.md
- lost-and-found-kata/src/main/java/org/eclipse/collections/lostandfoundkata/primitive/MinMaxPrimitivesBoxed.java
- lost-and-found-kata/src/main/java/org/eclipse/collections/lostandfoundkata/primitive/MinMaxPrimitivesPlain.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/MultiReaderCollectionsTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/multireader/SynchronizedCollectionsTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/BoxingTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/CollectionMemoryTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
> New set of tests for Lost and Found Kata.

- README.md
> Add solutions build badge to README.md.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/SynchronizedIntListTest.java
> Add SynchronizedIntListTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/UnmodifiableIntListTest.java
> Add UnmodifiableIntListTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntBagTest.java
> Add ImmutableIntBagTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntBagTest.java
> Add MutableIntBagTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntStackTest.java
> Add MutableIntStackTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntStackTest.java
> Add ImmutableIntStackTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntSetTest.java
> Add MutableIntSetTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
> Add ImmutableIntSetTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/LazyIntIterableTest.java
> Add LazyIntIterableTest to Lost and Found Kata.

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/StringAdaptersTest.java
> Add StringAdaptersTest to Lost and Found Kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BagTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BiMapTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/HashingStrategyTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/IntervalTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/MultimapTest.java
> Add nonjdk datastructures solutions to Lost and Founda Kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BagTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/HashingStrategyTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/IntervalTest.java
> Refactor datastructures solutions tests in Lost and Found Kata.

- .github/workflows/maven.yml
- .github/workflows/solutions.yml
> Add JDK 17 to actions builds.

- pom.xml
Signed-off-by: Samuel Hockenberry <Samuel.Hockenberry@bnymellon.com>
> Upgrade eclipse collections kata to 11.0.0.M6. Closes #212

- pom.xml
> Upgrade JUnit to 5.8.1.

- docs/candy-kata/slides.md
> Fix bug in Candy Kata slides with topOccurrences.

- pom.xml
> Upgrade eclipse-collections version to 11.0.0

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/MultimapTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/MultimapTest.java
> Split MultimapTest into smaller tests.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/IntervalTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/IntervalTest.java
> Split IntervalTest into smaller tests.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BiMapTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BiMapTest.java
> Split BiMapTest into smaller tests.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/LazyIntIterableTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/LazyIntIterableTest.java
> Refactor LazyIntIterableTest in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/StringAdaptersTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/StringAdaptersTest.java
> Refactor StringAdaptersTest in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
> Refactor ImmutableIntSetTest in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
> Refactor MutableIntListTest in lost-and-found-kata.

- docs/api-design/slides.md
Signed-off-by: Emilie Robichaud <emilie.robichaud@bnymellon.com>
> Update javadoc links in slides.md, closes #225

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntListTest.java
> Refactor ImmutableIntListTest in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntStackTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntStackTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntSetTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntStackTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntStackTest.java
> Refactor primitive Stack tests in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntSetTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntSetTest.java
> Refactor mutable primitive Set tests in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/SynchronizedIntListTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/SynchronizedIntListTest.java
> Refactor primitive synchronized List tests in lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntBagTest.java
- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntBagTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/immutable/ImmutableIntBagTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntBagTest.java
> Refactor primitive Bag tests for lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BagTest.java
> Add additional solutions for BagTest for lost-and-found-kata.

- lost-and-found-kata-solutions/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BagTest.java
- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/datastructures/BagTest.java
> Update BagTest in lost-and-found-kata with new tests.

- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise1Test.java
> Improve assertions in Pet Kata Exercise1Test.

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise1Test.java
> Improve assertions in Company kata Exercise1Test.

- company-kata-solutions/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
- company-kata/src/test/java/org/eclipse/collections/companykata/Exercise2Test.java
> Improve assertions in Customer kata Exercise2Test.

- .github/workflows/maven.yml
Signed-off-by: Aqsa Malik <aqsa.malik@bnymellon.com>
> update .yml files to fix JDK build issue

- pom.xml
> Upgrade JUnit and Jackson dependencies.

- pom.xml
Signed-off-by: Mike Marzo <michael.marzo@bnymellon.com>
> pom update for latest eclipse collections version. Closes #247

- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
- pet-kata-solutions/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise3Test.java
- pet-kata/src/test/java/org/eclipse/collections/petkata/Exercise4Test.java
> Add emoji tests to Pet Kata.

- top-methods-kata-solutions/src/main/java/org/eclipse/collections/topmethodskata/Fruit.java
- top-methods-kata-solutions/src/test/java/org/eclipse/collections/topmethodskata/Top25MethodsTest.java
- top-methods-kata/src/main/java/org/eclipse/collections/topmethodskata/Fruit.java
- top-methods-kata/src/test/java/org/eclipse/collections/topmethodskata/Top25MethodsTest.java
> Update Top 25 Methods kata with fruit emoji.

- pom.xml
> Updated Jackson dependency version to 2.14.1

- CONTRIBUTING.md
- README.md
- pom.xml
I added CONTRIBUTING.md file similar to the one in Eclipse Collections. I have been seeing contributions recently where the contributor has not signed the ECA, so I thought adding this file and a section in the README would help.
> Update README and add How to Contribute section.

- .github/workflows/maven.yml
Signed-off-by: Aqsa Malik [aqsa.malik@bnymellon.com](mailto:aqsa.malik@bnymellon.com)
> Update EA versions: 19,20 & 21

- README.md
The previous list of Katas did not include the Java 17 Katas. Started a list of the currently supported Java 17 Katas.
> Added Java 17 katas to README

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/LineItem.java
- company-kata/src/main/java/org/eclipse/collections/companykata/LineItem.java
So I am unsure how to test this. To make sure I haven't broken things. 
Cause I know I should be running the test and trying to make them pass but what test should I be running to make sure this hasn't broken anything haha
> fix issue #306 - remove unused imports

- pom-jdk17.xml
- pom.xml
Updated junit version from 5.9.2 to 5.10.0
> Update junit version to latest 5.10.0

- company-kata-solutions/src/main/java/org/eclipse/collections/companykata/Customer.java
- company-kata/src/main/java/org/eclipse/collections/companykata/Customer.java
Remove unused imports in Customer class in solutions module and in kata.
> Fixed issue #305 Remove unused imports in Customer class in solutions module and in kata

- haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorEC.java
- haiku-kata-solutions/src/test/java/org/eclipse/collections/haikukata/TextProcessorECTest.java
Added implementations of duplicatesAndUnique method in haiku-kata-solutions and updated the test case for the same.
> Fix issue #288 - added implementation of duplicatesAndUnique

- docs/api-design/slides.md
> Update documentation slides.md - issue #302

- haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorEC.java
- haiku-kata-solutions/src/test/java/org/eclipse/collections/haikukata/TextProcessorECTest.java
> Add TextProcessorEC.findWordleWords() 

- haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java
- haiku-kata/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java
> Fix typo in hint of TextProcessorJDK.topLetters() in both haiku-kata and haiku-kata-solutions module #299

- haiku-kata-solutions/src/main/java/org/eclipse/collections/haikukata/TextProcessorJDK.java
- haiku-kata-solutions/src/test/java/org/eclipse/collections/haikukata/TextProcessorJDKTest.java
> Add implementation to TextProcessorJDK.topVowelAndConsonant() for haiku-kata-solutions module #296

- haiku-kata/src/test/java/org/eclipse/collections/haikukata/TextProcessorECTest.java
- haiku-kata/src/test/java/org/eclipse/collections/haikukata/TextProcessorJDKTest.java
- wordle-kata/src/test/java/org/eclipse/collections/wordlekata/WordleECTest.java
- wordle-kata/src/test/java/org/eclipse/collections/wordlekata/WordleJDKTest.java
> Add tag to unit tests in Haiku and Wordle kata

- lost-and-found-kata/src/test/java/org/eclipse/collections/lostandfoundkata/primitive/mutable/MutableIntBagTest.java
Replacing with junit5 assertions in MutableIntBagTest class.
> Bug fix - update to junit5 assertions
